### ISSUE TITLE
Current Balance showing: $null

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#19]
When I tried to create a real bot, it failed & gave me this error 👇
ERROR: {"name":"AuthenticationError")

![Screenshot_3334.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/21cac009-347e-472a-8912-7448296c440e)

And also current Balance is showing null when I do have balance in kucoin 

![Screenshot_20231109-074833216.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/3e1282df-c90d-4cc0-8ac1-391367c96eea)

**Comment by 3cqs-coder** [comment]
Some exchanges can be confusing because of different requirements like a trading password and passphrase so first double check all of that is correct. You might also want to try for example, placing your apiPassphrase as apiPassword in the configuration file.

**Comment by REFLEXGAMING007** [comment]
It worked! thank you soo much

**Comment by REFLEXGAMING007** [comment]
New problem. I tried to open solana but it didn't go through. probably because minimum order quantity is too low. But currently it kinda stuck with the "Active dca bot deals" section with undefined values. How to remove it from there

![Screenshot_3351.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/28d64883-4a03-4f9f-883f-ddc9fbec1a71)

I can't cancel or close the deal to remove it from there.

![Screenshot_3352.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/5e393f01-6d3a-457a-a80e-c8a1a416b4e0)

![Screenshot_3353.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/851c7eda-7d4b-44cc-abb0-e7c781a1a5db)

By the way how to delete a dca bot from "manage dca bot" as well?

**Comment by REFLEXGAMING007** [comment]
I successfully opened deal with xrp🥳 but solana is still stuck in there.
![Screenshot_20231109-234522650.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/0771aa71-7e39-487d-bd30-9f6579dda72c)

**Comment by 3cqs-coder** [comment]
Thanks for the detail. Canceling the deal should remove it, but will try to debug what is causing the deals to stay active with invalid data.

**Comment by REFLEXGAMING007** [comment]
A lot of things happened in the past few hours while I was napping

I started a xrp deal few hours ago. When I woke up I saw it already exceeded the last updated time by 87minutes. Idk how that happened because I was only running 1 coin. there's no way it pressured on API
![Screenshot_20231110-042932496.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/19d3cbbb-be0a-4bec-9d75-7c5f7220889b)

After that I simply restarted the script & now it's in the undefined state. I also can't close or cancel the order just like the previous solana one. I had to sell that manually in kucoin because it's already way above my target.
![Screenshot_20231110-042628507.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/b1404db1-3f5a-45f2-94ad-df87a5702b51)

Now I have some questions

How to fix the exceeded the last updated time thing without getting glitched in undefined state?

Now both sol & xrp is currently stuck in undefined state glitch, how to fix that? Should I disable the bot & Re enable it or something else?

Also the exceeded the last updated time thing is kinda scary. Imagine a coin dumped but failed to get any safety orders because of that thing. Any possible solution to this risk? where that never happens again

I wish it stated why it couldn't update the deal, so that we identify & fix it.

**Comment by 3cqs-coder** [comment]
Please look at the logs for the XRP deal. The warnings for invalid data was recently added to make it much more obvious there is an issue, but the deal may have never started at all due to an issue on the initial buy order. The error messages in the logs will hopefully give more insight, and if this is the case, logic is already be looked into to cancel those deals and stop the bot.

**Comment by REFLEXGAMING007** [comment]
I just looked at the live logs. It's still trying to buy sol & trying to sell xrp
![Screenshot_20231110-052807204.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/5fea23f3-b914-4815-9f4c-b0dc83b6d8ee)

Is there a way to stop them from doing that without pressing the factory reset button?

Also my version is few days old, I have to update it apply those changes

**Comment by 3cqs-coder** [comment]
Thank you, this is very helpful. The SOL deal you were correct in saying the issue there is the quantity is too low. What's happening there, and currently being looked into, SymBot already created the deal, but nothing is happening with it due to the buy error, so it's just looping. In this case, the idea is to automatically cancel the deal and the bot will be stopped.

The XRP deal couldn't sell due to insufficient funds, which is likely due to exchange fees. This is where "exchangeFee" comes in and should be set high enough to give some leeway to make sure enough of the coin is always available for a successful take profit sell. The latest v0.99.450-beta.0 has some updated exchange fee logic that might resolve this for you, but some amounts you're using are sometimes so low, you might still see some sell errors. Hopefully not, but please post your findings. What is a little unclear is why the XRP deal is in an undefined state if it was able to buy for the initial order.

The SOL deal would probably be removed automatically with the auto-cancel deal logic mentioned above, but the XRP deal is still a bit of a mystery. The cancel deal functionality was added more recently to give the ability to remove deals easier, so that is the only method atm without doing an entire database reset, which hopefully is not needed.

Just want to thank you again for all the detail and comments, and will try as best as possible to get things working. But, please keep in mind the software is beta, there are many different exchange nuances, and please switch back and only use sandbox mode if you're not 100% comfortable with how things are functioning. Please do not risk using real trading.

**Comment by REFLEXGAMING007** [comment]
Thanks bro, I really appreciate the highly detailed reply. I'm gonna wipe everything, update the symbot & start fresh.

Also the reason xrp couldn't sell because I already sold them manually in kucoin after see the undefined thing.

Also one last question is there any possible solution currently available to avoid the exceeded last updated time scenario?

**Comment by 3cqs-coder** [comment]
I think the warning message might be a little misleading in this case. A large amount of focus in development is to make sure SymBot alerts you to any potential issue so you can it address as quickly as possible. Without those warnings, one may never look at the logs or even the web interface to realize there was ever an issue. If you never saw those alerts you might think there's no problem at all.

So those warnings are really generic in saying there is some issue with the deal or some unsuccessful response was received. In the XRP case, it couldn't sell. The original intention for the warning was if pricing couldn't be successfully polled it would count n minutes before sending a warning and reset the timer if everything resolved itself. But it's pretty clear in the future the warning messages should contain a bit more detail.  Ultimately if you get any warning or error messages, it's best to look at the logs immediately to see what's really happening.

**Comment by REFLEXGAMING007** [comment]
Okay, I understand now. Thanks again for the reply.

I'm gonna update & start fresh to see if this issue persists or not.

**Comment by REFLEXGAMING007** [comment]
KuCoin's trading fee is 0.08% so I'm supposed to set it 0.08 in the "exchangeFee" section of the bot config right?

**Comment by 3cqs-coder** [comment]
That's correct. You may want to try setting it higher if you encounter any sell errors.

**Comment by REFLEXGAMING007** [comment]
Need help again 😓
Symbot isn't resetting. 
At first I tried to create a new instance of SymBot from the updated files but it's failed by showing "server ID mismatch"

After that I decided to reset the old instance but it failed that as well. Cmd reset ended with showing bots reset **true** but deals reset **undefined** but neither of them got reset when I opened the web interface.

![Screenshot_3366.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/9e38c13f-460c-48a2-a2fd-f4d5c10a44d4)

It's still showing 4 deals in active deals section with 2 deals sometimes visible sometimes invisible for some reason.

![Screenshot_20231110-085629014.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/df164421-bb45-4419-954d-30c8bf5b16dd)

![Screenshot_20231110-092636409.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/c2ee814e-a878-47e3-8c70-c875764e7abd)

It's still doing the sol & xrp thing in live logs

![Screenshot_20231110-085822485.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/fae177a5-6414-4ee9-a485-8f48e36094a3)

What should I do in this situation? 
also everything's already updated in the above scenario

**Comment by 3cqs-coder** [comment]
SymBot is pretty strict when it comes to resetting the database as you can see, but it sounds like you might be pointing to multiple databases. For example, if you ever had multiple SymBot instances, one might be using mongodb://127.0.0.1:27017/SymBot and another might be using mongodb://127.0.0.1:27017/SymBot2. You would need to have the correct URL in app.json before resetting the correct database. You're still seeing deals since the data is still in the database you're pointing to.

You could use MongoDB shell (mongosh) on the command line to drop the database as a last resort. I do not want to encourage this approach to others by detailing instructions here, but if you choose to go this route, it's easily searchable on Google.
