### ISSUE TITLE
Bot price detection question, maybe bug

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#28]
So I was testing SymBot and in ICP/USDT pair the bot still didn't close the order even when the price touched it's target price (see graph) . Is it a bug?

![Screenshot_20231224-063025135_1.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/01bc1a8f-cdac-48d0-9d11-faf7dda234db)

![Screenshot_20231224-063036758_1.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/a696ee28-940b-422f-a001-39e2c30f5b55)

**Comment by 3cqs-coder** [comment]
There could be a few potential reasons. SymBot polls for pricing of each pair approximately every 1 second and also uses rate-limiting to help protect against situations like getting blocked by the exchange. So during times of increased volatility with a big wick like this, by the time pricing is polled, considering any delays with responses from the exchange, rate limits, etc. the price could easily change very quickly in those seconds. There are also considerations of other responses from the exchange including any order errors. The best way to determine what occurred is to look at the logs around that time. It's also best to be running the latest version of SymBot with up to date packages (npm) installed.

**Comment by REFLEXGAMING007** [comment]
Just asking, Is it possible to get the price from TradingView not from exchange so that we can use 500ms or 300ms refresh rate of price per pair for the bot? 

Like completely avoiding the need of exchange for price. All it have to do is press buttons 

OKX's dca bot is probably the best when it comes to Latency. They probably have less than 10ms latency for their bots. Opening & closing multiple deals in same second. I wonder if something like this is achievable here🤔

**Comment by 3cqs-coder** [comment]
There is no direct integration to TradingView for that, however getting pricing directly from the exchange is actually fastest since there's no middleman. SymBot uses one second by default to avoid potential issues with the exchanges mentioned earlier. In the future a customizable setting might be added to SymBot so you can specify the delay to what you're looking for. But keep in mind that can run into rate limiting issues and prevent running more bots and deals due to calling the exchange more frequently per deal.
