### ISSUE TITLE
Auth to coinbase not working

### ISSUE THREAD

**Issue by richardlhughes** [3cqs-coder/SymBot#32]
Hello,

Is there a way to get more logging to figure out why I cannot get the bots read my coinbase account?

![image](https://github.com/3cqs-coder/SymBot/assets/1203733/6b9e44f4-338e-4cf4-892b-8a32de1348a0)

I am at a loss on this one. I have tried several different approach to debug but, I am at a loss. Even tried different machines. 

I have created multiple api secret and key. I had a friend of mine try it on his bot and the key and secret are working on his build but, cannot find the problem on my end. 

Any help much appreciated. 

bot.json
```
{
    "apiKey": "204S*****qH4TbsE",
    "apiPassphrase": null,
    "apiPassword": null,
    "apiSecret": "0UWl7**********pzJvS4o2K",
    "dcaMaxOrder": 5,
    "dcaOrderAmount": 25,
    "dcaOrderSizeMultiplier": 1.08,
    "dcaOrderStartDistance": 1.3,
    "dcaOrderStepPercent": 1.3,
    "dcaOrderStepPercentMultiplier": 1.0,
    "dcaTakeProfitPercent": 3,
    "exchange": "coinbase",
    "exchangeFee": 0.6,
    "exchangeOptions": {
        "defaultType": "spot"
    },
    "firstOrderAmount": 20,
    "firstOrderLimitPrice": 150,
    "firstOrderType": "MARKET",
    "pair": "",
    "sandBox": false,
    "sandBoxWallet": 100000
}
```
app.json
```
{
    "password": "",
    "mongo_db_url": "mongodb://symbot:symbot123@database/symbot",
    "web_server": {
        "port": 3000
    },
    "api": {
        "enabled": true,
        "key": ""
    },
    "webhook": {
        "enabled": true
    },
    "telegram": {
        "enabled": true,
        "token_id": "67121550***************zozxRgdjS0",
        "notify_user_id": "68******8"
    },
    "bots": {
        "start_conditions": {
            "asap": {
                "description": "Open new trade asap"
            },
            "api": {
                "description": "Manually / API"
            }
        },
        "pair_autofill_buttons": [
            "USD",
            "USDT",
            "USDC"
        ],
        "pair_autofill_blacklist": [
            "BTC/*",
            "UST/*",
            "USD/*",
            "USDC/*",
            "USDD/*",
            "USDT/*"
        ]
    },
    "signals": {
        "3CQS": {
            "enabled": false,
            "api_key": ""
        }
    },
    "verbose_log": true
}
```

**Comment by 3cqs-coder** [comment]
Hi,

There are a few things to look at:

- By default SymBot has verbose logging enabled, so the full response to all interactions with the exchange will be in the logs. Since no pairs are returning, the logs should give more detail of what might be happening.
- You might also want to start using SymBot with: `npm start consolelog` to make it easier seeing everything on the console as it happens
- Try removing your exchange credentials, restart SymBot, and see if the same thing occurs. If so, there may be some type of connectivity issue or blocking. Take a look at the FAQ such as IPv6 related issues or IP address restrictions by the exchange.
- Double check your API key access settings / IP whitelist on the exchange.
- Try reinstalling modules with npm install
- Always leave `sandBox: true` even with your exchange credentials for testing purposes or real orders will be placed on the exchange.
- Be sure to pull the latest code

**Comment by guntoken** [comment]
Hi, I'm facing a similar problem. At first, I tried connecting to OKX exchanges but it didn't work. So, I switched to Kucoin exchanges instead. I believe Symbot should be able to connect with the exchange's API, but it shows my Current Balance as 'null'. Up until now, I haven't been able to connect to any crypto exchanges. Do you have any guides or instructions on how to make a connection with the exchanges?

**Comment by 3cqs-coder** [comment]
If you're able to see symbols populate when creating a bot without any errors displaying, then SymBot is actually successfully connecting to your exchange. If you're receiving any error messages and none of the above mentioned has helped, you might want to contact the exchange with the error message.

The balance showing as null is a bit confusing because SymBot is just defaulting to reading an available USDT balance from your exchange. If it doesn't detect any balance, it will show null. It is partly due to accounts that have many assets, so the exchange requires multiple calls with pagination, which SymBot will address in a future update.

**Comment by 3cqs-coder** [comment]
Closing as no further issues have been reported
